### PR TITLE
fix Makefile download-zig: url changed

### PR DESCRIPTION
**Pull request by lcoffe-botify**
This PR fixes the download URL for zig in the Makefile's download-zig rule.

### CODE REVIEW

**Comment by krichprollsch** [comment]
Hello @lcoffe-botify,
Thank you for your PR :pray: You are the first external contributor to the repo :tada: 

I'm putting it in on hold the time we configure a CLA for contribs on the repo.
Ofc after the change, we will be able to accept or refuse the CLA for your contribution.

Sorry for the delay...

**Comment by lucoffe** [comment]
no need to apologize, happy to contribute, even if it's just a line in a makefile 😆

**Comment by krichprollsch** [comment]
recheck

**Comment by krichprollsch** [comment]
@lcoffe-botify I integrated the CLA assistant.
Now you can read the [Lightpanda's CLA](https://github.com/lightpanda-io/browser/blob/main/CLA.md) and if you are agree with it, you can sign it :)

**Review by krichprollsch — APPROVED** [review]

**Comment by lucoffe** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
